---

version: "3.1"

services:

  s3:
    image: tomasbisi/s3server:supervisorcache
    ports:
      - "8000:8000"
      - "8100"
    networks:
      - connect

  frontend:
    image: tomasbisi/sentry_frontend:test4
    ports:
      - "5000:5000"
    networks:
      - connect

  backend:
    image: tomasbisi/sentry_backend
    ports:
      - "8200:8200"
    networks:
      - connect

  dynamodb:
    image: jibrankalia/dynamodb
    ports:
      - "8300"
    networks:
      - connect

  cache:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - connect

networks:
  connect:
