---

version: "3.1"

services:

  s3:
    image: tomasbisi/s3server:supervisorcache
    ports:
      - "8000:8000"
      - "8100"
    networks:
      - backend

  frontend:
    image: tomasbisi/sentry_frontend:final2
    ports:
      - "5000:5000"
    networks:
      - backend

  backend:
    image: tomasbisi/sentry_backend:final
    ports:
      - "8200:8200"
    networks:
      - backend

  dynamodb:
    image: jibrankalia/dynamodb
    ports:
      - "8300"
    networks:
      - backend

  cache:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - backend

networks:
  backend:
