---

version: "3.1"

services:
  frontend:
    image: tomasbisi/sentry_frontend:production
    ports:
      - "5000:5000"
    networks:
      - backend

  s3:
    image: tomasbisi/s3server:supervisorcache
    ports:
      - "8000"
      - "8100"
    networks:
      - backend

  backend:
    image: tomasbisi/sentry_backend
    ports:
      - "8200"
    networks:
      - backend

  dynamodb:
    image: jibrankalia/dynamodb
    ports:
      - "8300"
    networks:
      - backend

  cache:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - backend

networks:
  backend:
