---

version: "3.1"

services:
  s3:
    image: tomasbisi/s3server:supervisorcache
    ports:
      - "8000:8000"
      - "8100:8100"
    networks:
      - backend

  zenkoders:
    image: tomasbisi/zenkoders
    ports:
      - "8080:8080"
    networks:
      - backend

  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
